#!/bin/sh
#
# Mount and unmount all filesystems as a daemon
#

case "$1" in
    start)
        echo " :: Mounting all filesystems"

        # Mount /proc and /sys
        echo " ... Mounting /proc and /sys"
        /bin/mount -n -t proc none /proc
        /bin/mount -n -t sysfs none /sys

        # Mount root read-only
        echo " ... Mounting root read-only"
        /bin/mount -n -o remount,ro /

        # Check filesystems
        echo " ... Checking filesystems"
        /sbin/fsck -A -T -C -a
        ckret=$?

        # Fsck wants a reboot
        if [ $((${ckret}&2)) -eq 2 ]; then
            echo " ** System will reboot as required by fsck in 10 seconds"
            /bin/sleep 10
            /bin/umount -a
            /sbin/reboot -f
            exit 0
        fi

        # Check failed in general
        if [ ${ckret} -gt 1 -a ${ckret} -ne 32 ]; then
            echo " ** Filesystem check failed, please repair manually"
            /sbin/sulogin -p
            /bin/sleep 10
            /bin/umount -a
            /sbin/reboot -f
            exit 0
        fi

        # Mount root
        echo " ... Mounting root read-write"
        /bin/mount -n -o remount,rw /

        # Mount all other filesystems
        echo " ... Mounting all filesystems"
        /bin/mount -a

        # Activate all swap
        echo " ... Activating swap"
        /sbin/swapon -a
    ;;
    stop)
        echo " :: Unmounting all filesystems"

        # Write wtmp to disk
        /sbin/halt -w

        # Deactivate all swap
        echo " ... Deactivating swap"
        /sbin/swapoff -a

        # Unmount filesystems
        echo " ... Unmounting all filesystems"
        /bin/umount -a -r -t notmpfs,nosysfs,noproc -O no_netdev
    ;;
    *)
        echo "usage: $0 {start|stop}"
esac
