#!/bin/sh
#
# init.conf functions
# ---------------------
# Functions that can be used in init.conf
#

## Messages to console
# 

## Daemon management
# Start a daemon
startd(){
    for daemon in $@; do
        /usr/rc.d/$1 start
    done;
}

# Start a daemon in the background
startbkgd(){
    for daemon in $@; do
        (/usr/rc.d/$daemon start) &> /dev/null &
    done;
}

# Stop a daemon
stopd(){
    for daemon in $@; do
        /usr/rc.d/$daemon stop
    done;
}

# Stop all daemons
stop_daemons(){
    for daemon in $(/bin/ls -1t /var/run/daemons); do
        stopd $daemon
    done;
}

## Convenience functions
# Kill all processes
terminate_all(){
    # Get sleep times
    [ -z "$1" ] && post_sigterm="1" || post_sigterm="$1"
    [ -z "$2" ] && post_sigkill="1" || post_sigkill="$2"

    # Send sigterm
    echo " :: Sending SIGTERM to all running processes"
    /sbin/killall5 -15 &> /dev/null
    /bin/sleep $post_sigterm

    # Send sigkill
    echo " :: Sending SIGKILL to all running processes"
    /sbin/killall5 -9 &> /dev/null
    /bin/sleep $post_sigkill
}

# Halt entire system
system_halt(){
    if [ "$RUNLEVEL" = "0"]; then
        /sbin/poweroff -d -f -h -i
    else
        /sbin/reboot -d -f -i
    fi
}
